version: '3'
services: 
    app:
        build:
            context: ./backend
        volumes:
            - ./backend:/app
        ports:
            - 8001:8000
        depends_on:
            - db
        links:
            - "db:app"
    db:
        # build:
        #     context: ./backend
        #     dockerfile: Dockerfile-db
        image: postgres
        # ports:
        #     - 5432:5432
        restart: always
        environment:
            POSTGRES_PASSWORD: example