version: '3'
services: 
    app:
        build:
            context: ./backend/app
        volumes:
            - ./backend/app:/app
        ports:
            - 8001:8000
        depends_on:
            - db
            - tests
        environment: 
            - POSTGRES_USER=app
            - POSTGRES_PASSWORD=app
            - POSTGRES_SERVER=db
            - POSTGRES_DB=app
            - PYTHONPATH=/app
    tests:
        build:
            context: ./backend/app
            dockerfile: Dockerfile-tests
        volumes:
            - ./backend/app:/app
        depends_on: 
            - db_test
        environment: 
            - POSTGRES_USER=app
            - POSTGRES_PASSWORD=app
            - POSTGRES_SERVER=db_test
            - POSTGRES_DB=test_app
            - PYTHONPATH=/app
    db:
        image: postgres:12.4
        restart: always
        environment:
            # if user, pass, and db changes, need to remove previous containers # docker-compose rm -vf
            - POSTGRES_USER=app
            - POSTGRES_PASSWORD=app
    db_test:
        image: postgres:12.4
        restart: always
        environment:
            # if user, pass, and db changes, need to remove previous containers # docker-compose rm -vf
            - POSTGRES_USER=app
            - POSTGRES_PASSWORD=app
            - POSTGRES_DB=test_app