version: '3'
services: 
    app:
        build:
            context: ./backend/app
        volumes:
            - ./backend/app:/app
        ports:
            - 8001:8000
        depends_on:
            - db
            - tests
    tests:
        build:
            context: ./backend/app
            dockerfile: Dockerfile-tests
        volumes:
            - ./backend/app:/app
        depends_on: 
            - db
    db:
        image: postgres:12.4
        restart: always
        environment:
            # if user, pass, and db changes, need to remove previous containers # docker-compose rm -vf
            - POSTGRES_USER=app
            - POSTGRES_PASSWORD=app