version: '3'
services: 
    app:
        build:
            context: ./backend/app
        volumes:
            - ./backend/app:/app
        ports:
            - 8001:8000
        depends_on:
            - db
        links:
            - "db:app"
    db:
        image: postgres:12.4
        restart: always
        environment:
            POSTGRES_PASSWORD: example